// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetzGo.Agendamento.Infra.Contexto;

namespace PetzGo.Agendamento.Infra.Migrations
{
    [DbContext(typeof(AgendamentoContexto))]
    [Migration("20220320184255_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetzGo.Agendamento.Dominio.Entidades.Agenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgendaClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgendaPetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgendaServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgendamentoStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataHoraTermino")
                        .HasColumnType("datetime");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgendaClienteId")
                        .IsUnique()
                        .HasFilter("[AgendaClienteId] IS NOT NULL");

                    b.HasIndex("AgendaPetId")
                        .IsUnique()
                        .HasFilter("[AgendaPetId] IS NOT NULL");

                    b.HasIndex("AgendaServicoId")
                        .IsUnique()
                        .HasFilter("[AgendaServicoId] IS NOT NULL");

                    b.ToTable("Agenda");
                });

            modelBuilder.Entity("PetzGo.Agendamento.Dominio.Entidades.AgendaCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("AgendaCliente");
                });

            modelBuilder.Entity("PetzGo.Agendamento.Dominio.Entidades.AgendaPet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PetCaracteristica")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TipoPet")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AgendaPet");
                });

            modelBuilder.Entity("PetzGo.Agendamento.Dominio.Entidades.AgendaServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<int>("TempoEmMinutos")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("AgendaServico");
                });

            modelBuilder.Entity("PetzGo.Agendamento.Dominio.Entidades.Agenda", b =>
                {
                    b.HasOne("PetzGo.Agendamento.Dominio.Entidades.AgendaCliente", "AgendaCliente")
                        .WithOne("Agenda")
                        .HasForeignKey("PetzGo.Agendamento.Dominio.Entidades.Agenda", "AgendaClienteId");

                    b.HasOne("PetzGo.Agendamento.Dominio.Entidades.AgendaPet", "AgendaPet")
                        .WithOne("Agenda")
                        .HasForeignKey("PetzGo.Agendamento.Dominio.Entidades.Agenda", "AgendaPetId");

                    b.HasOne("PetzGo.Agendamento.Dominio.Entidades.AgendaServico", "AgendaServico")
                        .WithOne("Agenda")
                        .HasForeignKey("PetzGo.Agendamento.Dominio.Entidades.Agenda", "AgendaServicoId");

                    b.Navigation("AgendaCliente");

                    b.Navigation("AgendaPet");

                    b.Navigation("AgendaServico");
                });

            modelBuilder.Entity("PetzGo.Agendamento.Dominio.Entidades.AgendaCliente", b =>
                {
                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("PetzGo.Agendamento.Dominio.Entidades.AgendaPet", b =>
                {
                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("PetzGo.Agendamento.Dominio.Entidades.AgendaServico", b =>
                {
                    b.Navigation("Agenda");
                });
#pragma warning restore 612, 618
        }
    }
}
