// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetzGo.Cadastros.Infra.Contexto;

namespace PetzGo.Cadastros.Infra.Migrations
{
    [DbContext(typeof(CadastrosContexto))]
    [Migration("20210925220222_Criando-Novas-Entidades")]
    partial class CriandoNovasEntidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.DiaSemana", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoDiaSemana")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiaSemana");

                    b.HasData(
                        new
                        {
                            Id = new Guid("831fe066-848d-4c6b-a1d0-1e441a498544"),
                            TipoDiaSemana = 0
                        },
                        new
                        {
                            Id = new Guid("13654bc3-fe85-4630-afa1-a9d850d859bf"),
                            TipoDiaSemana = 1
                        },
                        new
                        {
                            Id = new Guid("b3035ced-91cf-437b-ae44-7ae743b053b8"),
                            TipoDiaSemana = 2
                        },
                        new
                        {
                            Id = new Guid("fad12262-7436-46b6-a2a0-a190a14d7e4e"),
                            TipoDiaSemana = 3
                        },
                        new
                        {
                            Id = new Guid("52feb789-b47f-4a60-ad45-dbb8a6210e08"),
                            TipoDiaSemana = 4
                        },
                        new
                        {
                            Id = new Guid("b661b3e3-f373-48a0-9419-ba0d459a7cce"),
                            TipoDiaSemana = 5
                        },
                        new
                        {
                            Id = new Guid("b481195e-bad5-4797-b1c6-74bd420fdcb9"),
                            TipoDiaSemana = 6
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<Guid?>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RotuloLink")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("TipoNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique()
                        .HasFilter("[EnderecoId] IS NOT NULL");

                    b.HasIndex("TipoNegocioId");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.EmpresaHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiaSemanaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HoraFim")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("DiaSemanaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("EmpresaHorario");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.EmpresaServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServicoPetCaracteristicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoEmMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("TipoPet")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ServicoPetCaracteristicaId");

                    b.ToTable("EmpresaServico");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(40)");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<Guid>("PetCaracteristicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoPet")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("PetCaracteristicaId");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.PetCaracteristica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoPetCaracteristica")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PetCaracteristica");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a4f87ea-fbda-46d0-963c-a70e9491995c"),
                            TipoPetCaracteristica = 0
                        },
                        new
                        {
                            Id = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            TipoPetCaracteristica = 1
                        },
                        new
                        {
                            Id = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            TipoPetCaracteristica = 2
                        },
                        new
                        {
                            Id = new Guid("4c3d8bff-7488-4560-bd1d-da6b38e8feb3"),
                            TipoPetCaracteristica = 3
                        },
                        new
                        {
                            Id = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            TipoPetCaracteristica = 4
                        },
                        new
                        {
                            Id = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            TipoPetCaracteristica = 5
                        },
                        new
                        {
                            Id = new Guid("2858d9ad-6f9d-46a9-b34a-7cd179730c9f"),
                            TipoPetCaracteristica = 6
                        },
                        new
                        {
                            Id = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            TipoPetCaracteristica = 7
                        },
                        new
                        {
                            Id = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            TipoPetCaracteristica = 8
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Servico");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33"),
                            Nome = "Banho"
                        },
                        new
                        {
                            Id = new Guid("acfae699-460a-43b3-8b3d-86928fe61388"),
                            Nome = "Banho & Tosa com máquina"
                        },
                        new
                        {
                            Id = new Guid("eb665260-cac8-4869-a03e-35770f8bf119"),
                            Nome = "Banho & Tosa com tesoura"
                        },
                        new
                        {
                            Id = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1"),
                            Nome = "Tosa com máquina"
                        },
                        new
                        {
                            Id = new Guid("79563a4a-5d26-4440-9afb-314453257ee5"),
                            Nome = "Tosa com tesoura"
                        },
                        new
                        {
                            Id = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd"),
                            Nome = "Tosa higiênica"
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.ServicoPetCaracteristica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PetCaracteristicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PetCaracteristicaId");

                    b.HasIndex("ServicoId");

                    b.ToTable("ServicoPetCaracteristica");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf87fb8e-4f65-4ccf-bf94-7052d1edc6ac"),
                            PetCaracteristicaId = new Guid("5a4f87ea-fbda-46d0-963c-a70e9491995c"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("814fb496-5fc5-4a48-a85d-691ec125c186"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("b0c59363-9110-44cf-9636-313c701a7b27"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("2748f2dc-6e7d-4122-b48e-5c9d971b95e2"),
                            PetCaracteristicaId = new Guid("4c3d8bff-7488-4560-bd1d-da6b38e8feb3"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("f4c17a25-092f-493c-a0d6-1c19433f62d1"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("0d18b2cd-37e0-4501-b605-1236f8043aea"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("746d12d0-811c-4d07-a8e4-f3185e12a22b"),
                            PetCaracteristicaId = new Guid("2858d9ad-6f9d-46a9-b34a-7cd179730c9f"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("764851f6-0aee-48ab-ae53-8ae413de7746"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("35fdb5c6-d5a9-4846-8794-b474e981074f"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("a06125c5-f073-4952-9460-c1d9cc8aeb6c"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("c19061a5-238c-4ec0-bf41-72efcc13376a"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("ca8690af-93b2-432e-9888-b6a63f860d6b"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("c4a94970-b752-4e8e-95da-e0d2c759893c"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("e3e88ee7-113c-4844-bec8-9c86ef4f7673"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("149e5a1b-e714-457a-aaaa-8fb5a97d6336"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("9422215b-dd6c-4fe8-a5ed-5e3dc915fda2"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("a6dc1ff8-1ce8-460b-b1e0-17f58ee2065e"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("9995db60-1248-4152-90c1-3cd70fa00f6b"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("8245fde7-3792-4c88-89c7-f5c112772a08"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("196ea67d-3cf7-4ac4-ab45-6fc212253c6f"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("69506058-3243-4ab3-a6c1-662b38e1b88d"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("d70d6bfb-bdab-445c-9974-603e5663a971"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("2daac770-a2c6-41f6-b571-54d538fb3b0b"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("3e409e80-092d-4340-843c-e7b8cbca4f88"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("58451281-3ac0-4ef9-b4d9-25ba4f3377ed"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("5d411e23-3b94-4626-93a4-dbea939c08f3"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("bf12932f-912d-4776-8ec1-d43972fc4b3c"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("df228944-d519-464f-9f0b-446e68c06cd3"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("943cf5e7-13fb-4476-9b2a-00b01c30cb86"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("99fffab6-9523-4049-a8d8-7f12f2756ba1"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("737a4705-08b5-405f-9ce9-3b40db0c6735"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("06de729a-af51-40d5-92f0-f0d210802ca2"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("a644c97f-5019-4c3a-a4a8-5ef379bc2f9e"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("0aa797f7-9234-4543-ab0f-5f32abf9c3a8"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("9bc46552-2356-47a4-ae33-6bc55fdf82dd"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("ca14fa63-7e2e-4d15-92e0-3352a98a70e3"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("5d4124db-b45c-43c5-836d-6907b733916d"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("396976a8-2087-48a7-a07d-b3570fb5ab6a"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("15697276-54e3-47d7-af43-450f299f2b24"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.TipoNegocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeTipoNegocio")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TipoNegocio");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ed433bb-5687-4b00-9d1b-84717101ac48"),
                            NomeTipoNegocio = "PetShop"
                        },
                        new
                        {
                            Id = new Guid("ce280415-4d18-4637-9244-7b76b69274a4"),
                            NomeTipoNegocio = "ClinicaVeterinaria"
                        },
                        new
                        {
                            Id = new Guid("ef4565e5-b230-4182-89f1-0ebfc1e26563"),
                            NomeTipoNegocio = "PetShopClinicaVeterinaria"
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Cliente", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Endereco", "Endereco")
                        .WithOne("Cliente")
                        .HasForeignKey("PetzGo.Cadastros.Dominio.Entidades.Cliente", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Empresa", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Endereco", "Endereco")
                        .WithOne("Empresa")
                        .HasForeignKey("PetzGo.Cadastros.Dominio.Entidades.Empresa", "EnderecoId");

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.TipoNegocio", "TipoNegocio")
                        .WithMany("Empresas")
                        .HasForeignKey("TipoNegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("TipoNegocio");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.EmpresaHorario", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.DiaSemana", "DiaSemana")
                        .WithMany("EmpresaHorarios")
                        .HasForeignKey("DiaSemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Empresa", "Empresa")
                        .WithMany("EmpresaHorarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaSemana");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.EmpresaServico", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Empresa", "Empresa")
                        .WithMany("EmpresaServicos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.ServicoPetCaracteristica", "ServicoPetCaracteristica")
                        .WithMany("EmpresaServico")
                        .HasForeignKey("ServicoPetCaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("ServicoPetCaracteristica");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Pet", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Cliente", "Cliente")
                        .WithOne("Pet")
                        .HasForeignKey("PetzGo.Cadastros.Dominio.Entidades.Pet", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.PetCaracteristica", "PetCaracteristica")
                        .WithMany("Pets")
                        .HasForeignKey("PetCaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("PetCaracteristica");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.ServicoPetCaracteristica", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.PetCaracteristica", "PetCaracteristica")
                        .WithMany("ServicoPetCaracteristica")
                        .HasForeignKey("PetCaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Servico", "Servico")
                        .WithMany("ServicoPetCaracteristica")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetCaracteristica");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Cliente", b =>
                {
                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.DiaSemana", b =>
                {
                    b.Navigation("EmpresaHorarios");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Empresa", b =>
                {
                    b.Navigation("EmpresaHorarios");

                    b.Navigation("EmpresaServicos");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Endereco", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.PetCaracteristica", b =>
                {
                    b.Navigation("Pets");

                    b.Navigation("ServicoPetCaracteristica");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Servico", b =>
                {
                    b.Navigation("ServicoPetCaracteristica");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.ServicoPetCaracteristica", b =>
                {
                    b.Navigation("EmpresaServico");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.TipoNegocio", b =>
                {
                    b.Navigation("Empresas");
                });
#pragma warning restore 612, 618
        }
    }
}
