// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetzGo.Cadastros.Infra.Contexto;

namespace PetzGo.Cadastros.Infra.Migrations
{
    [DbContext(typeof(CadastrosContexto))]
    [Migration("20210926191908_adicionando-bool-cliente")]
    partial class adicionandoboolcliente
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.DiaSemana", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoDiaSemana")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiaSemana");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f921c12e-2f07-4fed-b285-9198d6510ce4"),
                            TipoDiaSemana = 0
                        },
                        new
                        {
                            Id = new Guid("899c5cfd-923a-4267-8af5-f6262f8e7393"),
                            TipoDiaSemana = 1
                        },
                        new
                        {
                            Id = new Guid("18091b7f-1550-439e-9ec2-86a261709ff0"),
                            TipoDiaSemana = 2
                        },
                        new
                        {
                            Id = new Guid("41cd00c0-f662-47ee-b104-b8773eabcf64"),
                            TipoDiaSemana = 3
                        },
                        new
                        {
                            Id = new Guid("c554c92c-80d4-44fb-b4c8-3526427bd59e"),
                            TipoDiaSemana = 4
                        },
                        new
                        {
                            Id = new Guid("d688615d-755c-4984-8ed1-46107cd9d923"),
                            TipoDiaSemana = 5
                        },
                        new
                        {
                            Id = new Guid("67ae7ce6-3ca5-47ea-9f31-d8a597664bc2"),
                            TipoDiaSemana = 6
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<Guid?>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RotuloLink")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("TipoNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique()
                        .HasFilter("[EnderecoId] IS NOT NULL");

                    b.HasIndex("TipoNegocioId");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.EmpresaHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiaSemanaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HoraFim")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("DiaSemanaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("EmpresaHorario");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.EmpresaServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServicoPetCaracteristicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoEmMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("TipoPet")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ServicoPetCaracteristicaId");

                    b.ToTable("EmpresaServico");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Estado")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<Guid>("PetCaracteristicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoPet")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("PetCaracteristicaId");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.PetCaracteristica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoPetCaracteristica")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PetCaracteristica");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a4f87ea-fbda-46d0-963c-a70e9491995c"),
                            TipoPetCaracteristica = 0
                        },
                        new
                        {
                            Id = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            TipoPetCaracteristica = 1
                        },
                        new
                        {
                            Id = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            TipoPetCaracteristica = 2
                        },
                        new
                        {
                            Id = new Guid("4c3d8bff-7488-4560-bd1d-da6b38e8feb3"),
                            TipoPetCaracteristica = 3
                        },
                        new
                        {
                            Id = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            TipoPetCaracteristica = 4
                        },
                        new
                        {
                            Id = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            TipoPetCaracteristica = 5
                        },
                        new
                        {
                            Id = new Guid("2858d9ad-6f9d-46a9-b34a-7cd179730c9f"),
                            TipoPetCaracteristica = 6
                        },
                        new
                        {
                            Id = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            TipoPetCaracteristica = 7
                        },
                        new
                        {
                            Id = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            TipoPetCaracteristica = 8
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Servico");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33"),
                            Nome = "Banho"
                        },
                        new
                        {
                            Id = new Guid("acfae699-460a-43b3-8b3d-86928fe61388"),
                            Nome = "Banho & Tosa com máquina"
                        },
                        new
                        {
                            Id = new Guid("eb665260-cac8-4869-a03e-35770f8bf119"),
                            Nome = "Banho & Tosa com tesoura"
                        },
                        new
                        {
                            Id = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1"),
                            Nome = "Tosa com máquina"
                        },
                        new
                        {
                            Id = new Guid("79563a4a-5d26-4440-9afb-314453257ee5"),
                            Nome = "Tosa com tesoura"
                        },
                        new
                        {
                            Id = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd"),
                            Nome = "Tosa higiênica"
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.ServicoPetCaracteristica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PetCaracteristicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PetCaracteristicaId");

                    b.HasIndex("ServicoId");

                    b.ToTable("ServicoPetCaracteristica");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af27a61b-6749-4fff-8ebb-5d2900bd2897"),
                            PetCaracteristicaId = new Guid("5a4f87ea-fbda-46d0-963c-a70e9491995c"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("12345565-6e51-4a08-8798-bac84266dd5f"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("fca87f12-6e45-4cbc-8cfc-bfd443c57786"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("d06ecd6e-fce2-4b81-861e-edd5cac84f08"),
                            PetCaracteristicaId = new Guid("4c3d8bff-7488-4560-bd1d-da6b38e8feb3"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("e637da38-8cbd-47b9-bba2-6eb602694256"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("ed141839-273d-437a-be60-1c2437665b35"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("e3532f76-380e-47d4-a093-64697c5d4ec5"),
                            PetCaracteristicaId = new Guid("2858d9ad-6f9d-46a9-b34a-7cd179730c9f"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("122015d6-eca0-494e-a2a8-2664f8fdb24b"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("f788a376-60fe-405a-af8a-c89f9a63c437"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("d576217b-848d-47e2-a3cb-8c2945b20c23"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("7a72b1e7-877b-40cf-957c-76edc22bf053"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("456fd09d-acdb-4bf2-81c6-8a4123a868d4"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("e1f07b8e-a3f1-4f97-b35b-8e5a1b90097a"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("ec24c6e6-284d-427d-a835-bdb13dc384cd"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("c2605e54-ad4f-462c-9e67-06559db7572b"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("9b98989e-205e-4f9b-8228-603d3e5efee0"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("0584b2e5-cd35-4914-b499-475f2a63a9fd"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("fff372e2-1d77-4c7a-a408-8c25ce6b81b4"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("4b68e062-88a6-4d76-9ee0-82a492863285"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("8d6ab660-008a-4b27-9252-2b2cbb036664"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("ce7567a5-81b0-472a-a417-6148da419e05"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("712c188f-fc3c-47fb-9124-50d6c081baa6"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("3a5c366a-e712-4cec-8478-24bbde85e908"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("c5471cce-82c3-4160-b638-62093d3dbf5f"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("05b89539-4324-4313-b3ad-9460f47ade3b"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("61c65380-6107-4c84-b17b-07b506bd8daa"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("1e4332cd-8e12-42a5-9a0e-2ccee3386a0c"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("5a142252-66e2-47b4-8b25-1aba5c2685c1"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("f2386bd8-0d1e-441a-bde8-bb6b8ffe54c2"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("8b26c965-6b2a-4364-9141-bcf98ac435c6"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("2ec3c0ac-570a-4966-9fd7-9efd846ff29b"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("e53fa2cc-3e55-4eb6-aa81-1c32d92d60f8"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("71eed2b5-954b-472f-98c0-f5fb1c7a8c5d"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("613ddd8e-7cdb-4bf5-ba09-fc1ac732acef"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("67d8f191-a41b-451d-b44d-2febf9221c58"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("33feb591-f482-4644-a80b-fb980e7fc715"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("de57e81f-77d1-4ce9-9f59-e653deb20831"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("b57d4d0c-0f81-4468-8166-a4c277292ed4"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("7425cb7c-24f8-4604-9433-f37c2b8093bd"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.TipoNegocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeTipoNegocio")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TipoNegocio");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ed433bb-5687-4b00-9d1b-84717101ac48"),
                            NomeTipoNegocio = "PetShop"
                        },
                        new
                        {
                            Id = new Guid("ce280415-4d18-4637-9244-7b76b69274a4"),
                            NomeTipoNegocio = "ClinicaVeterinaria"
                        },
                        new
                        {
                            Id = new Guid("ef4565e5-b230-4182-89f1-0ebfc1e26563"),
                            NomeTipoNegocio = "PetShopClinicaVeterinaria"
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Cliente", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Endereco", "Endereco")
                        .WithOne("Cliente")
                        .HasForeignKey("PetzGo.Cadastros.Dominio.Entidades.Cliente", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Empresa", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Endereco", "Endereco")
                        .WithOne("Empresa")
                        .HasForeignKey("PetzGo.Cadastros.Dominio.Entidades.Empresa", "EnderecoId");

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.TipoNegocio", "TipoNegocio")
                        .WithMany("Empresas")
                        .HasForeignKey("TipoNegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("TipoNegocio");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.EmpresaHorario", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.DiaSemana", "DiaSemana")
                        .WithMany("EmpresaHorarios")
                        .HasForeignKey("DiaSemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Empresa", "Empresa")
                        .WithMany("EmpresaHorarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaSemana");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.EmpresaServico", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Empresa", "Empresa")
                        .WithMany("EmpresaServicos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.ServicoPetCaracteristica", "ServicoPetCaracteristica")
                        .WithMany("EmpresaServico")
                        .HasForeignKey("ServicoPetCaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("ServicoPetCaracteristica");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Pet", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Cliente", "Cliente")
                        .WithOne("Pet")
                        .HasForeignKey("PetzGo.Cadastros.Dominio.Entidades.Pet", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.PetCaracteristica", "PetCaracteristica")
                        .WithMany("Pets")
                        .HasForeignKey("PetCaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("PetCaracteristica");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.ServicoPetCaracteristica", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.PetCaracteristica", "PetCaracteristica")
                        .WithMany("ServicoPetCaracteristica")
                        .HasForeignKey("PetCaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Servico", "Servico")
                        .WithMany("ServicoPetCaracteristica")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetCaracteristica");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Cliente", b =>
                {
                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.DiaSemana", b =>
                {
                    b.Navigation("EmpresaHorarios");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Empresa", b =>
                {
                    b.Navigation("EmpresaHorarios");

                    b.Navigation("EmpresaServicos");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Endereco", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.PetCaracteristica", b =>
                {
                    b.Navigation("Pets");

                    b.Navigation("ServicoPetCaracteristica");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Servico", b =>
                {
                    b.Navigation("ServicoPetCaracteristica");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.ServicoPetCaracteristica", b =>
                {
                    b.Navigation("EmpresaServico");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.TipoNegocio", b =>
                {
                    b.Navigation("Empresas");
                });
#pragma warning restore 612, 618
        }
    }
}
