// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetzGo.Cadastros.Infra.Contexto;

namespace PetzGo.Cadastros.Infra.Migrations
{
    [DbContext(typeof(CadastrosContexto))]
    [Migration("20210926160734_Teste-Migracao")]
    partial class TesteMigracao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.DiaSemana", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoDiaSemana")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiaSemana");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c4af785-e90b-4df6-bc5d-174981f793ca"),
                            TipoDiaSemana = 0
                        },
                        new
                        {
                            Id = new Guid("84ae9ba2-77cc-43be-9166-6200a755933b"),
                            TipoDiaSemana = 1
                        },
                        new
                        {
                            Id = new Guid("f3c507e0-4eca-439f-9d38-99a9da52940e"),
                            TipoDiaSemana = 2
                        },
                        new
                        {
                            Id = new Guid("3199a724-bd9d-4e7b-9b35-03167d329bf1"),
                            TipoDiaSemana = 3
                        },
                        new
                        {
                            Id = new Guid("f4a5f261-0223-46a2-9216-504473934c90"),
                            TipoDiaSemana = 4
                        },
                        new
                        {
                            Id = new Guid("6515aa99-9bad-4a8c-910e-82ff15f6ce8d"),
                            TipoDiaSemana = 5
                        },
                        new
                        {
                            Id = new Guid("b9f7a41d-f679-407c-bf30-4c8ae81d34f2"),
                            TipoDiaSemana = 6
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<Guid?>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RotuloLink")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("TipoNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique()
                        .HasFilter("[EnderecoId] IS NOT NULL");

                    b.HasIndex("TipoNegocioId");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.EmpresaHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DiaSemanaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HoraFim")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("DiaSemanaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("EmpresaHorario");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.EmpresaServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServicoPetCaracteristicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TempoEmMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("TipoPet")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ServicoPetCaracteristicaId");

                    b.ToTable("EmpresaServico");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Estado")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(70)");

                    b.Property<Guid>("PetCaracteristicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoPet")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("PetCaracteristicaId");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.PetCaracteristica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoPetCaracteristica")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PetCaracteristica");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a4f87ea-fbda-46d0-963c-a70e9491995c"),
                            TipoPetCaracteristica = 0
                        },
                        new
                        {
                            Id = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            TipoPetCaracteristica = 1
                        },
                        new
                        {
                            Id = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            TipoPetCaracteristica = 2
                        },
                        new
                        {
                            Id = new Guid("4c3d8bff-7488-4560-bd1d-da6b38e8feb3"),
                            TipoPetCaracteristica = 3
                        },
                        new
                        {
                            Id = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            TipoPetCaracteristica = 4
                        },
                        new
                        {
                            Id = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            TipoPetCaracteristica = 5
                        },
                        new
                        {
                            Id = new Guid("2858d9ad-6f9d-46a9-b34a-7cd179730c9f"),
                            TipoPetCaracteristica = 6
                        },
                        new
                        {
                            Id = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            TipoPetCaracteristica = 7
                        },
                        new
                        {
                            Id = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            TipoPetCaracteristica = 8
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Servico");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33"),
                            Nome = "Banho"
                        },
                        new
                        {
                            Id = new Guid("acfae699-460a-43b3-8b3d-86928fe61388"),
                            Nome = "Banho & Tosa com máquina"
                        },
                        new
                        {
                            Id = new Guid("eb665260-cac8-4869-a03e-35770f8bf119"),
                            Nome = "Banho & Tosa com tesoura"
                        },
                        new
                        {
                            Id = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1"),
                            Nome = "Tosa com máquina"
                        },
                        new
                        {
                            Id = new Guid("79563a4a-5d26-4440-9afb-314453257ee5"),
                            Nome = "Tosa com tesoura"
                        },
                        new
                        {
                            Id = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd"),
                            Nome = "Tosa higiênica"
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.ServicoPetCaracteristica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PetCaracteristicaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PetCaracteristicaId");

                    b.HasIndex("ServicoId");

                    b.ToTable("ServicoPetCaracteristica");

                    b.HasData(
                        new
                        {
                            Id = new Guid("539fef25-8b7a-4817-a8ae-7c9efff7ed4e"),
                            PetCaracteristicaId = new Guid("5a4f87ea-fbda-46d0-963c-a70e9491995c"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("8d9c02e7-b44c-4bc4-8612-da00a5ef3b12"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("9b528339-7f16-4d64-aa44-510300d58f86"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("6b73d110-6011-43cf-950c-984a274ce387"),
                            PetCaracteristicaId = new Guid("4c3d8bff-7488-4560-bd1d-da6b38e8feb3"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("9227cdf8-c12d-4d7f-958b-6804c680d0ad"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("f8b6d5d4-45d4-43a6-a9b4-a1d477fd413a"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("c168cc6b-4a68-4139-992e-83cad2a42bff"),
                            PetCaracteristicaId = new Guid("2858d9ad-6f9d-46a9-b34a-7cd179730c9f"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("66fd27ec-82fe-45cb-a618-0dee9849f83e"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("c50f025c-2b5b-46ba-9b18-82656e905a68"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("cf2c0c60-9398-4011-a8fb-11815c292c33")
                        },
                        new
                        {
                            Id = new Guid("f5cec5f1-c5ff-4b6a-a34c-571b664c76fb"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("f6bb8b6c-9063-42a4-96a6-25e975da08e0"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("34caf77d-62fe-4b9c-993f-c0a51b744101"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("6a876bf3-1770-4b42-a233-5be0c088ef9c"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("4b05e1a1-c9a9-46ad-b72e-3589ffc38fa5"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("913285a5-574b-4a30-9c5e-7453263d66be"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("acfae699-460a-43b3-8b3d-86928fe61388")
                        },
                        new
                        {
                            Id = new Guid("7deb0eaf-35d0-48b7-a596-5a1f9908364e"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("c6837b18-4c64-499c-a1c5-7b12d4fe25bd"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("5497efe1-d5d1-41bb-94ff-67d400ef86db"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("1ba8e954-a400-4e24-a9e6-c7059499b950"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("370dac50-b164-47e8-85a2-ec79f0a47b3f"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("71545d07-0c64-4fbe-9000-05f52b24188d"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("eb665260-cac8-4869-a03e-35770f8bf119")
                        },
                        new
                        {
                            Id = new Guid("b16c44d9-7d4d-4f92-b8e4-1fd80e7d4106"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("fe9a4164-740a-41cb-8e67-3a3bc8a1d9fd"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("96806485-7aed-444e-ac52-3fa8a0b5556d"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("f2c08d81-3861-4a3f-bf00-34d96b6f0f69"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("d0ece339-2c83-4e4e-a44f-e587a242234a"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("b6ce42f3-fc69-415a-8d2e-235c730677e0"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("26a8223b-fbe5-49fd-a7ba-99e6f00470c1")
                        },
                        new
                        {
                            Id = new Guid("92a054a5-a70d-4a69-b8b5-3aef0131d714"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("6ac5316d-65d6-4ece-9d8c-597747e8618f"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("e2460f32-7f0a-455b-ac50-d132db2ca113"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("81106e6f-5abe-488b-a368-d0ee214983d2"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("4f38a386-3749-420f-8156-e55ed03cea5a"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("0f61053d-826f-4a18-94df-54b9785bc2c8"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("79563a4a-5d26-4440-9afb-314453257ee5")
                        },
                        new
                        {
                            Id = new Guid("5555edcc-06a2-4341-9973-9cf74394b919"),
                            PetCaracteristicaId = new Guid("e97ce00f-62b6-4e8e-8150-500318d6b5d3"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("5433831b-0b00-4f48-946a-19d20d4194d9"),
                            PetCaracteristicaId = new Guid("fdf62227-c47a-40e7-8a29-d4fb59a37051"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("c60432ed-2940-414b-a785-97f8194e177a"),
                            PetCaracteristicaId = new Guid("088f3ab6-360c-4e9c-8841-bdf503b3ecd4"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("e59bfdfd-9639-4b94-bdd1-3a9df93126f8"),
                            PetCaracteristicaId = new Guid("c1dbfa76-1415-4776-b49e-897ffa76621c"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("473240cf-47c9-42b6-8e9b-9dd0817316d4"),
                            PetCaracteristicaId = new Guid("b7bf1e6d-ece5-486e-a966-1daadf1b30f7"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        },
                        new
                        {
                            Id = new Guid("01162be9-db85-43d4-b63a-948eb9d8fad3"),
                            PetCaracteristicaId = new Guid("65e23e78-af21-42e6-a805-648c9eee1ef1"),
                            ServicoId = new Guid("7f453ac3-b51f-4281-973b-50181ec273fd")
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.TipoNegocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeTipoNegocio")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TipoNegocio");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ed433bb-5687-4b00-9d1b-84717101ac48"),
                            NomeTipoNegocio = "PetShop"
                        },
                        new
                        {
                            Id = new Guid("ce280415-4d18-4637-9244-7b76b69274a4"),
                            NomeTipoNegocio = "ClinicaVeterinaria"
                        },
                        new
                        {
                            Id = new Guid("ef4565e5-b230-4182-89f1-0ebfc1e26563"),
                            NomeTipoNegocio = "PetShopClinicaVeterinaria"
                        });
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Cliente", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Endereco", "Endereco")
                        .WithOne("Cliente")
                        .HasForeignKey("PetzGo.Cadastros.Dominio.Entidades.Cliente", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Empresa", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Endereco", "Endereco")
                        .WithOne("Empresa")
                        .HasForeignKey("PetzGo.Cadastros.Dominio.Entidades.Empresa", "EnderecoId");

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.TipoNegocio", "TipoNegocio")
                        .WithMany("Empresas")
                        .HasForeignKey("TipoNegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("TipoNegocio");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.EmpresaHorario", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.DiaSemana", "DiaSemana")
                        .WithMany("EmpresaHorarios")
                        .HasForeignKey("DiaSemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Empresa", "Empresa")
                        .WithMany("EmpresaHorarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaSemana");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.EmpresaServico", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Empresa", "Empresa")
                        .WithMany("EmpresaServicos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.ServicoPetCaracteristica", "ServicoPetCaracteristica")
                        .WithMany("EmpresaServico")
                        .HasForeignKey("ServicoPetCaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("ServicoPetCaracteristica");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Pet", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Cliente", "Cliente")
                        .WithOne("Pet")
                        .HasForeignKey("PetzGo.Cadastros.Dominio.Entidades.Pet", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.PetCaracteristica", "PetCaracteristica")
                        .WithMany("Pets")
                        .HasForeignKey("PetCaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("PetCaracteristica");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.ServicoPetCaracteristica", b =>
                {
                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.PetCaracteristica", "PetCaracteristica")
                        .WithMany("ServicoPetCaracteristica")
                        .HasForeignKey("PetCaracteristicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetzGo.Cadastros.Dominio.Entidades.Servico", "Servico")
                        .WithMany("ServicoPetCaracteristica")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetCaracteristica");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Cliente", b =>
                {
                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.DiaSemana", b =>
                {
                    b.Navigation("EmpresaHorarios");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Empresa", b =>
                {
                    b.Navigation("EmpresaHorarios");

                    b.Navigation("EmpresaServicos");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Endereco", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.PetCaracteristica", b =>
                {
                    b.Navigation("Pets");

                    b.Navigation("ServicoPetCaracteristica");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.Servico", b =>
                {
                    b.Navigation("ServicoPetCaracteristica");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.ServicoPetCaracteristica", b =>
                {
                    b.Navigation("EmpresaServico");
                });

            modelBuilder.Entity("PetzGo.Cadastros.Dominio.Entidades.TipoNegocio", b =>
                {
                    b.Navigation("Empresas");
                });
#pragma warning restore 612, 618
        }
    }
}
